a = input("Hello would")
name = input("Victoria")
age = input("16")
lastname = input("Kkhviruk")
print = ("a:", type(a))
print = ("name:", type(name))
print = ("age:", type(age))
print = ("lastname:", type(lastname))
